---
# tasks file for php

    - name: Update cache and Install LEMP Packages
      apt: 
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'php-fpm', 'php-mysql', 'python3-pymysql' ]
